# Generated by Django 4.2.7 on 2023-11-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteAvail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_time', models.DateTimeField()),
                ('url', models.CharField(max_length=100)),
                ('regex', models.CharField(default='', max_length=50)),
                ('status_code', models.CharField(max_length=10)),
                ('time_elapsed', models.CharField(max_length=10)),
                ('is_match_regex', models.BooleanField(default=False)),
            ],
        ),
    ]
